---
- name: Redmine Server
  hosts: redmine
  become: true
  vars_files:
    - proxy.yml
  environment: "{{ proxy_env }}"
  roles:
    - ../ansible_common/common
    - ../ansible_common/ruby
    - { role: ../ansible_common/postgres, db_name: redmine, db_passwd: "{{ db_passwd_redmine }}" }
    - redmine
    - passenger
    - jenkins
    - { role: ../ansible_common/firewalld, SERVICES:["http"], PORTS:["8080/tcp"] }
