---
- name: delete Gemfile.lock
  file: path={{ redmine_dir }}/Gemfile.lock state=absent

- name: install plugin gems
  command:
    bundle install --without xapian --no-deployment
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production

- name: update gems
  command:
    bundle update
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production

- name: migrate redmine-database
  command:
    bundle exec rake db:migrate
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production

- name: migrate plugins-database
  command:
    bundle exec rake redmine:plugins:migrate
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production
