---
- name: Set common initial settings
  command:
    bundle exec rails r '{{ item }}'
    chdir={{ redmine_dir }}
  with_items:
    # Locale
    - 'Setting["default_language"]="{{ redmine_locale }}"'
    - 'Setting["repositories_encodings"]="UTF-8,CP932,EUC-JP"'
    # Default Theme
    - 'Setting["ui_theme"]="minimalflat2"'
    - 'Setting["thumbnails_enabled"]="1"'
    # REST API
    - 'Setting["rest_api_enabled"]="1"'
    # Login
    - 'Setting["login_required"]="1"'
    - 'Setting["autologin"]="1"'
    - 'Setting["lost_password"]="1"'
    # User Registration
    - 'Setting["self_registration"]="0"'
    - 'Setting["password_min_length"]="8"'
    # Project
    - 'Setting["default_projects_public"]="0"'
    - 'Setting["unsubscribe"]="1"'
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production

# In some countries, name order is FAMILY-NAME INDIVIDUAL-NAME.
# Typical countries are Japan, Koria, China, Hungary.
- name: Set name order
  command:
    bundle exec rails r '{{ item }}'
    chdir={{ redmine_dir }}
  with_items:
    - 'Setting["user_format"]="lastname_firstname"'
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production
  when: 'redmine_locale in ["ja","kr","kp","cn","tw","hu"]'
