---
#- name: install farend_basic theme
#  git:
#    repo=https://github.com/farend/redmine_theme_farend_basic.git
#    dest={{ redmine_dir }}/public/themes/farend_basic

- name: install gitmike theme
  git:
    repo=https://github.com/makotokw/redmine-theme-gitmike.git
    dest={{ redmine_dir }}/public/themes/gitmike

- name: download themes
  get_url: 
    url="{{ item }}"
    dest=/tmp
    validate_certs=no
  with_items:
    - https://github.com/akabekobeko/redmine-theme-minimalflat2/releases/download/v1.3.6/minimalflat2-1.3.6.zip

- name: install themes
  unarchive:
    src="/tmp/{{ item }}"
    dest={{ redmine_dir }}/public/themes
    remote_src=yes
  with_items:
    - minimalflat2-1.3.6.zip
