---
- name: "jenkins yum repository"
  yum_repository:
    name: jenkins
    description: "jenkins YUM repo"
    baseurl: "http://pkg.jenkins-ci.org/redhat-stable/"

- name: "jenkins-ci.org.key installed"
  rpm_key:
    key: "http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key"

- name: Install jenkins
  yum: name={{ item }}  state=present
  with_items:
    - java-1.8.0-openjdk-devel
    - maven
    - ant
    - groovy
    - jenkins

- name: Start jenkins service
  service:
    name: jenkins
    state: started
    enabled: yes
